# Generated by Django 2.2.25 on 2022-09-02 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_overviews", "0024_overview_adds_has_highlights"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseManage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("product_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="Product ID")),
                (
                    "course",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_overviews.CourseOverview",
                    ),
                ),
            ],
            options={
                "verbose_name": "CourseManage",
                "verbose_name_plural": "Course Management",
            },
        ),
    ]
